Enhance CI workflow to include coverage checks and ensure minimum coverage before deployment

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -8,31 +8,38 @@ on:
       - main
 
 jobs:
-  # CI job for testing and linting
+  # CI job for testing, linting, and checking coverage
   ci:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      - name: Checkout repository
         uses: actions/checkout@v2
-      - name: setup node
+      - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: 20
+          node-version: "20"
       - name: Install dependencies
-        run: npm install
-      - name: Run Line
+        run: npm ci
+      - name: Run lint
         run: npm run lint
-        # continue-on-error: false
-      - name: Run Test
-        run: npm run test
-        # continue-on-error: false
-      - name: Run Build
-        run: npm run build
+      - name: Run tests with coverage
+        run: |
+          npm test -- --coverage
+      - name: Check test coverage
+        run: |
+          # Check if Jest coverage is above 75%
+          COVERAGE=$(grep -oP 'All files.*\K\d+(?=%)' coverage/lcov-report/index.html)
+          echo "Test coverage is ${COVERAGE}%"
+          if [ "$COVERAGE" -lt 75 ]; then
+            echo "Test coverage is below 75%. Aborting deployment."
+            exit 1
+          fi
 
   # Build and deploy job
-  cd:
+  build_and_deploy:
     runs-on: ubuntu-latest
-    needs: ci
+    needs: ci # Ensure the CI job runs successfully before deploying
+    if: success() # Only run this job if the previous job (ci) succeeded
     steps:
       - uses: actions/checkout@v2
       - run: npm ci && npm run build
